sudo: required
dist: trusty

services:
  - elasticsearch

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - postfix
    - oracle-java9-set-default

language: php

jobs:
  include:
# Elasticsearch 6
    - php: 7.2
      env:
          - ES_VERSION=6.8.8 MAGENTO_VERSION=2.3.5-p1 MAGENTO_EDITION=community
    - if: type != pull_request
      php: 7.2
      env:
          - ES_VERSION=6.8.8 MAGENTO_VERSION=2.3.5-p1 MAGENTO_EDITION=enterprise
    - php: 7.3
      env:
          - ES_VERSION=6.8.8 MAGENTO_VERSION=2.3.5-p1 MAGENTO_EDITION=community
    - if: type != pull_request
      php: 7.3
      env:
          - ES_VERSION=6.8.8 MAGENTO_VERSION=2.3.5-p1 MAGENTO_EDITION=enterprise
# Elasticsearch 7
    - php: 7.2
      env:
          - ES_VERSION=7.6.2-amd64 MAGENTO_VERSION=2.3.5-p1 MAGENTO_EDITION=community
    - if: type != pull_request
      php: 7.2
      env:
          - ES_VERSION=7.6.2-amd64 MAGENTO_VERSION=2.3.5-p1 MAGENTO_EDITION=enterprise
    - php: 7.3
      env:
          - ES_VERSION=7.6.2-amd64 MAGENTO_VERSION=2.3.5-p1 MAGENTO_EDITION=community
    - if: type != pull_request
      php: 7.3
      env:
          - ES_VERSION=7.6.2-amd64 MAGENTO_VERSION=2.3.5-p1 MAGENTO_EDITION=enterprise

before_install:
  - sudo service elasticsearch stop
  - export ES_HOME=/usr/share/elasticsearch
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$ES_VERSION.deb
  - sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb
  - yes | sudo $ES_HOME/bin/elasticsearch-plugin install analysis-icu
  - yes | sudo $ES_HOME/bin/elasticsearch-plugin install analysis-phonetic
  - sudo chgrp elasticsearch /etc/default/elasticsearch -R
  - sudo service elasticsearch start
  - sleep 5
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then composer config -g http-basic.repo.magento.com $MAGENTO_USERNAME $MAGENTO_PASSWORD ; fi
  - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
  - if [ -n "$GH_ACCESS_TOKEN" ]; then composer config github-oauth.github.com ${GH_ACCESS_TOKEN}; fi;
  - composer global require hirak/prestissimo:0.3.10
  - chmod +x ./Resources/travis/*
  - ./Resources/travis/prepare_php.sh
  - ./Resources/travis/prepare_apache.sh
  - ./Resources/travis/prepare_graphql.sh
  - ./Resources/travis/before_install.sh

install:
  - composer install --prefer-dist

cache:
  directories:
    - $HOME/.composer/cache

script:
  - ./Resources/travis/test_magento.sh
  - ./Resources/travis/test_data.sh
  - ./Resources/travis/test_web.sh
  - ./Resources/travis/test_graphql.sh
  - vendor/bin/phpcs --config-set installed_paths vendor/magento/marketplace-eqp/
  - vendor/bin/phpcs --standard=vendor/magento/marketplace-eqp/MEQP2 --severity=9 src/
  - vendor/bin/phpcs --standard=vendor/smile/magento2-smilelab-phpcs/phpcs-standards/SmileLab --extensions=php src/
  - vendor/bin/phpmd src text vendor/smile/magento2-smilelab-phpmd/phpmd-rulesets/rulset.xml
  - vendor/bin/phpunit -c Resources/tests/unit/phpunit.xml

after_failure:
    - sudo cat /var/log/apache2/apache-error.log
